package fr.erick.journallocal;

/** Generated by tools/generate_config.py; edit config/defaults.json. Public values only. */
public final class AivConfig {
    private AivConfig() {}
    public static final String SHA256="93108f8d2a146bfcdc92984cf6b9031b7aee204b36c411d465cd2318cf9f70ad";
    public static final int WORK_EVENTS=16;
    public static final int WORK_VERIFY_ROWS=128;
    public static final int WORK_STATS_ROWS=64;
    public static final int WORK_SLICE_MS=40;
    public static final int WORK_MIN_PAUSE_MS=1000;
    public static final int ANOMALY_WINDOW_MS=300000;
    public static final int ANOMALY_GROUP_MS=900000;
    public static final int ANOMALY_FAILURE_COUNT_DEFAULT=8;
    public static final int ANOMALY_UPLOAD_MIB_DEFAULT=10;
    public static final int COLLECTION_GAP_MS=150000;
    public static final int COLLECTION_CLOCK_DRIFT_MS=5000;
    public static final int COLLECTION_INVENTORY_INTERVAL_MS=900000;
    public static final int COLLECTION_HEARTBEAT_MS=60000;
    public static final int MAIN_INVENTORY_MAX_AGE_MS=86400000;
    public static final int MAIN_THRESHOLD_BYTES_DEFAULT=10485760;
    public static final int MAIN_CONFIG_MAX_CHARS=32768;
    public static final int MAIN_LIST_MAX_ITEMS=100;
    public static final int REFERENCE_IMPORT_MAX_BYTES=16777216;
    public static final int REFERENCE_MAX_APPS=20000;
    public static final int REFERENCE_APP_MAX_CHARS=262144;
    public static final int REFERENCE_MAX_EXPECTED_IPS=100;
    public static final int CONTROL_BATCH_MAX_APPS=50;
    public static final int CONTROL_REQUEST_MAX_CHARS=16384;
    public static final int CONTROL_PREVIEW_VALID_MS=300000;
    public static final int CONTROL_COMMAND_TIMEOUT_MS=12000;
    public static final int CONTROL_OUTPUT_MAX_BYTES=16384;
    public static final int CONTROL_REPORT_MAX_BYTES=8388608;
    public static final int CONTROL_WATCH_MAX_FAILURES=3;
    public static final String PATHS_EXPORTS_CACHE="exports";
    public static final String PATHS_CLEANUP_SNAPSHOT="aiv-shizuku-cleanup-last.json";
    public static final String PATHS_CONTROL_REPORTS="control-reports";
    public static final String PATHS_CONTROL_DRAFT="draft.json";
    public static final String PATHS_CONTROL_PREFERENCES="developer-control";
}
