package fr.erick.journallocal;

/** Generated by tools/generate_config.py; edit config/defaults.json. Public values only. */
public final class AivConfig {
    private AivConfig() {}
    public static final String SHA256="65718fc3e03439d86f875db10c5df370f0994536a190dad894880ca5734fa7aa";
    public static final int WORK_EVENTS=16;
    public static final int WORK_VERIFY_ROWS=128;
    public static final int WORK_STATS_ROWS=64;
    public static final int WORK_SLICE_MS=40;
    public static final int WORK_MIN_PAUSE_MS=1000;
    public static final int ANOMALY_WINDOW_MS=300000;
    public static final int ANOMALY_GROUP_MS=900000;
    public static final int ANOMALY_FAILURE_COUNT_DEFAULT=8;
    public static final int ANOMALY_UPLOAD_MIB_DEFAULT=10;
    public static final int COLLECTION_GAP_MS=150000;
    public static final int COLLECTION_CLOCK_DRIFT_MS=5000;
    public static final int COLLECTION_INVENTORY_INTERVAL_MS=900000;
    public static final int COLLECTION_HEARTBEAT_MS=60000;
    public static final int MAIN_INVENTORY_MAX_AGE_MS=86400000;
    public static final int MAIN_THRESHOLD_BYTES_DEFAULT=10485760;
    public static final int MAIN_CONFIG_MAX_CHARS=32768;
    public static final int MAIN_LIST_MAX_ITEMS=100;
    public static final int REFERENCE_IMPORT_MAX_BYTES=16777216;
    public static final int REFERENCE_MAX_APPS=20000;
    public static final int REFERENCE_APP_MAX_CHARS=262144;
    public static final int REFERENCE_MAX_EXPECTED_IPS=100;
    public static final String PATHS_EXPORTS_CACHE="exports";
    public static final String PATHS_CLEANUP_SNAPSHOT="aiv-shizuku-cleanup-last.json";
}
