#!/usr/bin/env python3
"""Execute production node/snapshot/event mapping against synthetic accessibility nodes.
This checks bounded traversal and recycling; it is not a device AccessibilityService test.
"""
from pathlib import Path
import os,subprocess,tempfile
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'app/src/main/java/fr/erick/journallocal/ScreenIntegrityService.java'
def extract(s,signature):
 start=s.index(signature);end=s.index('{',start)+1;depth=1
 while depth:
  depth+=(s[end]=='{')-(s[end]=='}');end+=1
 return s[start:end]
s=SOURCE.read_text();methods='\n'.join(extract(s,x) for x in ('static String kind(', 'static String eventKind(', 'static long eventElapsed(', 'private static String clean(', 'static JSONObject node(', 'static JSONObject snapshot(', 'private static String hex('))
stubs={
'android/graphics/Rect.java':'''package android.graphics;public class Rect{public int left,top,right,bottom;public Rect(){}public Rect(int l,int t,int r,int b){left=l;top=t;right=r;bottom=b;}}''',
'android/view/accessibility/AccessibilityEvent.java':'''package android.view.accessibility;public class AccessibilityEvent{public static final int TYPE_VIEW_CLICKED=1,TYPE_WINDOW_STATE_CHANGED=32,TYPE_WINDOWS_CHANGED=4194304,TYPE_VIEW_SELECTED=4,TYPE_VIEW_TEXT_CHANGED=16,TYPE_VIEW_SCROLLED=4096,TYPE_VIEW_FOCUSED=8;}''',
'android/view/accessibility/AccessibilityNodeInfo.java':'''package android.view.accessibility;import android.graphics.Rect;import java.util.*;public class AccessibilityNodeInfo{public static int obtained,recycled;public String text="",description="",clazz="Button",view="id";public boolean editable,password,visible=true,clickable=true,scrollable;public final List<AccessibilityNodeInfo> children=new ArrayList<>();public Rect bounds=new Rect(1,2,30,40);public static AccessibilityNodeInfo obtain(AccessibilityNodeInfo n){obtained++;AccessibilityNodeInfo copy=new AccessibilityNodeInfo();copy.text=n.text;copy.description=n.description;copy.clazz=n.clazz;copy.view=n.view;copy.editable=n.editable;copy.password=n.password;copy.visible=n.visible;copy.clickable=n.clickable;copy.scrollable=n.scrollable;copy.bounds=n.bounds;copy.children.addAll(n.children);return copy;}public void recycle(){recycled++;}public void getBoundsInScreen(Rect out){out.left=bounds.left;out.top=bounds.top;out.right=bounds.right;out.bottom=bounds.bottom;}public CharSequence getText(){return text;}public CharSequence getContentDescription(){return description;}public CharSequence getClassName(){return clazz;}public String getViewIdResourceName(){return view;}public boolean isSelected(){return false;}public boolean isChecked(){return false;}public boolean isCheckable(){return false;}public boolean isFocused(){return false;}public boolean isEnabled(){return true;}public boolean isPassword(){return password;}public boolean isEditable(){return editable;}public boolean isVisibleToUser(){return visible;}public boolean isClickable(){return clickable;}public boolean isScrollable(){return scrollable;}public int getChildCount(){return children.size();}public AccessibilityNodeInfo getChild(int i){return obtain(children.get(i));}public List<AccessibilityAction> getActionList(){return Arrays.asList(new AccessibilityAction());}public static class AccessibilityAction{public int getId(){return 16;}}}''',
'fr/erick/journallocal/EventStore.java':'''package fr.erick.journallocal;import org.json.*;class EventStore{static JSONObject object(Object... parts){JSONObject o=new JSONObject();for(int i=0;i<parts.length;i+=2)o.put(String.valueOf(parts[i]),parts[i+1]);return o;}}'''
}
probe='''package fr.erick.journallocal;import android.graphics.Rect;import android.view.accessibility.*;import org.json.*;import java.util.*;import java.security.MessageDigest;
public class SemanticProbe{__METHODS__ static int checks;static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}public static void main(String[] args)throws Exception{AccessibilityNodeInfo root=new AccessibilityNodeInfo();root.text="Télécharger";root.description="Action";JSONObject n=node(root);check(n.getJSONArray("bounds").getInt(2)==30&&n.getBoolean("clickable")&&n.getJSONArray("actions").getInt(0)==16,"element bounds/actions lost");check(n.getString("text").equals("Télécharger")&&n.getString("content_description").equals("Action"),"semantic labels lost");root.editable=true;check(node(root).getString("text").equals("[CHAMP MASQUÉ]")&&node(root).getString("content_description").isEmpty(),"editable private contents recorded");root.editable=false;root.password=true;check(node(root).getString("text").equals("[CHAMP MASQUÉ]"),"password recorded");root.password=false;
for(int i=0;i<64;i++){AccessibilityNodeInfo child=new AccessibilityNodeInfo();root.children.add(child);for(int j=0;j<10;j++)child.children.add(new AccessibilityNodeInfo());}JSONObject snap=snapshot(root);check(snap.getInt("nodes")==256&&snap.getJSONArray("tree").length()==48,"snapshot unbounded");check(AccessibilityNodeInfo.obtained==AccessibilityNodeInfo.recycled,"bounded traversal leaked queued nodes");check(snap.getString("hash").length()==64&&snapshot(root).getString("hash").equals(snap.getString("hash")),"snapshot hash unstable");check(kind(1).equals("CLICK")&&kind(32).equals("WINDOW_CHANGE")&&kind(4194304).equals("WINDOW_CHANGE")&&kind(4).equals("SELECTION"),"click/window/selection mapping lost");check(eventKind(16,true).equals("PACKAGE_CHANGE")&&eventKind(1,true).equals("CLICK"),"package change or click lost");check(eventElapsed(280000,100000,99700)==279700&&eventElapsed(280000,100000,100100)==280000,"uptime incorrectly treated as elapsedRealtime");System.out.println("Accessibility production snapshot: "+checks+" checks passed");}}
'''.replace('__METHODS__',methods)
with tempfile.TemporaryDirectory() as folder:
 root=Path(folder);src=root/'src';classes=root/'classes';classes.mkdir()
 for name,body in stubs.items():
  p=src/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(body)
 (src/'fr/erick/journallocal/SemanticProbe.java').write_text(probe)
 jar=os.environ['AIV_JSON_JAR'];subprocess.run(['javac','-encoding','UTF-8','-cp',jar,'-d',str(classes),*map(str,src.rglob('*.java'))],check=True,timeout=30);subprocess.run(['java','-cp',str(classes)+os.pathsep+jar,'fr.erick.journallocal.SemanticProbe'],check=True,timeout=30)
