#!/usr/bin/env python3
"""Production correlation, analysis SQLite, endpoint ledger and evidence policies.
Android UI/Keystore/screenshots require device validation; these are deterministic host tests.
"""
from pathlib import Path
import ast, os, subprocess, tempfile
ROOT=Path(__file__).resolve().parents[1]; JAVA=ROOT/'app/src/main/java/fr/erick/journallocal'
cp=os.pathsep.join(os.environ[k] for k in ('AIV_JSON_JAR','AIV_SQLITE_JAR','AIV_SLF4J_JAR'))
tree=ast.parse((ROOT/'tests/journal-sqlite.py').read_text());base=ast.literal_eval(next(n.value for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='stubs' for t in n.targets)))
stubs={k:v for k,v in base.items() if k.startswith('android/')}
stubs['android/database/Cursor.java']=stubs['android/database/Cursor.java'].replace('public boolean isNull','public byte[] getBlob(int i){return (byte[])rows.get(position)[i];}public boolean isNull')
s=stubs['android/database/sqlite/SQLiteDatabase.java'].replace('CONFLICT_REPLACE=5','CONFLICT_REPLACE=5,CONFLICT_IGNORE=4')
s=s.replace('return 1;}','try(Cursor c=rawQuery("SELECT last_insert_rowid()",null)){c.moveToFirst();return c.getLong(0);}}',1)
s=s.replace('public int delete(','''public int update(String table,ContentValues values,String where,String[] args){java.util.List<Object> all=new java.util.ArrayList<>(values.values());if(args!=null)java.util.Collections.addAll(all,args);java.util.List<String> set=new java.util.ArrayList<>();for(String key:values.keySet())set.add(key+"=?");execSQL("UPDATE "+table+" SET "+String.join(",",set)+" WHERE "+where,all.toArray());return 1;}public int delete(''')
stubs['android/database/sqlite/SQLiteDatabase.java']=s
stubs['android/content/SharedPreferences.java']='''package android.content;import java.util.*;public class SharedPreferences{Map<String,String> values=new HashMap<>();public String getString(String k,String d){return values.getOrDefault(k,d);}public Editor edit(){return new Editor();}public class Editor{public Editor putString(String k,String v){values.put(k,v);return this;}public boolean commit(){return true;}}}'''
stubs['android/content/Context.java']='''package android.content;import java.io.File;public class Context{public static final int MODE_PRIVATE=0;public final File root;private final SharedPreferences preferences=new SharedPreferences();public Context(File r){root=r;root.mkdirs();}public Context getApplicationContext(){return this;}public SharedPreferences getSharedPreferences(String name,int mode){return preferences;}}'''
stubs.update({
'fr/erick/journallocal/EventStore.java':'''package fr.erick.journallocal;import org.json.*;import android.content.Context;class EventStore{static JSONArray events=new JSONArray();static EventStore instance=new EventStore();static EventStore get(Context c){return instance;}static String clockScope(){return "fixture";}static JSONObject object(Object... parts){JSONObject o=new JSONObject();for(int i=0;i<parts.length;i+=2)o.put(String.valueOf(parts[i]),parts[i+1]);return o;}JSONArray analysisBatch(long after,int limit){JSONArray out=new JSONArray();for(int i=0;i<events.length();i++)if(events.getJSONObject(i).optLong("id")>after&&out.length()<limit)out.put(events.getJSONObject(i));return out;}long latestId(){return events.length();}JSONArray evidence(JSONArray ids){JSONArray out=new JSONArray();for(int i=0;i<events.length();i++)for(int j=0;j<ids.length();j++)if(events.getJSONObject(i).optLong("id")==ids.optLong(j))out.put(events.getJSONObject(i));return out;}}''',
'fr/erick/journallocal/ScreenIntegrityService.java':'''package fr.erick.journallocal;import org.json.*;class ScreenIntegrityService{static int notifications,committed;static void findingsChanged(){notifications++;}static void findingCommitted(long id,JSONObject f){try{if(ConvergenceProbe.monitor.finding(id).getLong("id")!=id)throw new AssertionError("alert before persistence");committed++;}catch(Exception e){throw new AssertionError(e);}}}''',
'fr/erick/journallocal/PermissionUsage.java':'''package fr.erick.journallocal;import android.content.Context;import org.json.*;class PermissionUsage{static PermissionUsage get(Context c){return new PermissionUsage();}JSONObject status(){return new JSONObject();}static void enrich(Context c,JSONArray rows){}static JSONObject anomalyContext(Context c,JSONArray rows){return new JSONObject();}}''',
'fr/erick/journallocal/NetworkReport.java':'''package fr.erick.journallocal;import android.content.Context;import org.json.*;class NetworkReport{static void enrich(Context c,JSONObject e){}static JSONObject anomalyContext(JSONArray events){return new JSONObject();}}'''
})
probe=r'''package fr.erick.journallocal;
import android.content.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.io.*;import java.lang.reflect.*;import java.util.*;
public class ConvergenceProbe{
 static AnomalyMonitor monitor;static int checks;static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static JSONObject event(long id,String cat,long elapsed){JSONObject identity=EventStore.object("uid",10371,"package_name","example.chat","app_identity_id","cert","current_signer_sha256",new JSONArray().put("synthetic-certificate"),"first_install_ms",1,"version_code",218);return EventStore.object("id",id,"timestamp_ms",100000+elapsed,"elapsed_ms",elapsed,"clock_scope_id","fixture","category",cat,"app","Fixture","destination","192.0.2.1:443","details",EventStore.object("uid",10371,"packages",new JSONArray().put("example.chat"),"app_identity",identity,"protocol","TCP","port",443,"tls_sni","api.example.org","remote_ip","192.0.2.1","flow_correlation_id","flow-"+id,"flow_id","flow-"+id,"outbound_observed",true,"inbound_observed",true));}
 static void baseRules()throws Exception{
  JSONObject click=event(1,"frontend",1000);ConvergenceRules.details(click).put("event_kind","CLICK").put("package_name","example.chat").put("element",EventStore.object("text","Partager","bounds",new JSONArray(Arrays.asList(1,2,30,40))));
  JSONObject op=event(2,"acces",1200);ConvergenceRules.details(op).put("operation","READ_CONTACTS").put("access_result","ACCESS").put("usage_observation_id","op-1");JSONObject network=event(3,"trafic",1400);
  check(ConvergenceRules.sameNear(op,network,3000),"same actor rejected");JSONObject other=event(4,"trafic",1400);ConvergenceRules.details(other).put("uid",10372);check(!ConvergenceRules.sameNear(op,other,3000),"wrong UID linked");
  other=event(4,"trafic",1400);ConvergenceRules.details(other).getJSONObject("app_identity").put("app_identity_id","other");check(!ConvergenceRules.sameNear(op,other,3000),"wrong signer linked");
  other=event(4,"trafic",1400);ConvergenceRules.details(other).put("packages",new JSONArray().put("different.app"));check(!ConvergenceRules.sameNear(op,other,3000),"wrong package linked");
  other=event(4,"trafic",1400).put("clock_scope_id","reboot");check(!ConvergenceRules.sameNear(op,other,3000),"reboot linked");
  network.put("timestamp_ms",900000000);check(ConvergenceRules.sameNear(op,network,3000),"wall clock defeated monotonic");
  ConvergenceRules rules=new ConvergenceRules();check(rules.accept(click).isEmpty()&&rules.accept(op).isEmpty(),"finding before network");List<JSONObject> findings=rules.accept(network);check(findings.size()==1,"front/back finding missing");JSONObject finding=findings.get(0);check(finding.getJSONArray("evidence_ids").length()==3&&finding.getJSONArray("timeline").length()==3,"source timeline missing");check(finding.getJSONObject("conclusion").getJSONArray("unknown").length()>0,"payload claim invented");check(rules.accept(network).isEmpty(),"duplicate alert");
  rules=new ConvergenceRules();rules.accept(click);JSONObject capability=event(5,"permissions",1200);ConvergenceRules.details(capability).put("permission_granted",true).put("operation","READ_CONTACTS");rules.accept(capability);check(rules.accept(network).isEmpty(),"grant became activity");
  rules=new ConvergenceRules();rules.accept(click);ConvergenceRules.details(op).put("access_result","REJECT");rules.accept(op);check(rules.accept(network).isEmpty(),"reject became usage");
  check(ConvergenceRules.profile(network,false,true).getString("status").equals("OFFICIAL_IDENTIFIED"),"official service unresolved");check(ConvergenceRules.profile(network,false,false).getString("status").equals("NEW_FOR_APP"),"new host lost");check(ConvergenceRules.profile(network,true,false).getString("status").equals("KNOWN_FOR_APP"),"history lost");ConvergenceRules.details(network).put("tls_sni","");check(ConvergenceRules.profile(network,true,true).getString("status").equals("SHARED_INFRASTRUCTURE"),"CDN IP overattributed");
  JSONObject unresolved=event(9,"trafic",1500);ConvergenceRules.details(unresolved).getJSONObject("app_identity").remove("current_signer_sha256");check(ConvergenceRules.actorKey(unresolved).isEmpty(),"missing signer attributed");ConvergenceRules.details(unresolved).put("identity_conflict",true);check(ConvergenceRules.profile(unresolved,false,false).getString("status").equals("DIVERGENT"),"identity conflict hidden");
  JSONObject frontend=new JSONObject(ConvergenceRules.details(click).toString()).put("element_source","EVENT_NODE").put("window_id",7).put("clock_scope_id","fixture").put("captured_elapsed_ms",1000);frontend.getJSONObject("element").put("visible",true).put("class","Button").put("text","Partager").put("content_description","").put("view_id","share");
  check(OverlayRules.highlightReason(frontend,7,"example.chat","fixture",1400,true).equals("READY"),"matching live bounds not highlighted");
  check(OverlayRules.highlightReason(frontend,8,"example.chat","fixture",1400,true).equals("WINDOW_CHANGED")&&OverlayRules.highlightReason(frontend,7,"other.app","fixture",1400,true).equals("WINDOW_CHANGED"),"highlight crossed app/window");
  check(OverlayRules.highlightReason(frontend,7,"example.chat","reboot",1400,true).equals("CLOCK_SCOPE_CHANGED")&&OverlayRules.highlightReason(frontend,7,"example.chat","fixture",7000,true).equals("ELEMENT_EXPIRED"),"stale/reboot highlight accepted");
  check(OverlayRules.highlightReason(frontend,7,"example.chat","fixture",1400,false).equals("ELEMENT_NOT_PRESENT")&&OverlayRules.highlightReason(null,7,"example.chat","fixture",1400,true).equals("NO_LINKED_ELEMENT"),"missing element invented");
  JSONObject target=frontend.getJSONObject("element"),changed=new JSONObject(target.toString());check(OverlayRules.matchesElement(target,changed),"same node lost");changed.put("content_description","Other action");check(!OverlayRules.matchesElement(target,changed),"changed action framed");changed=new JSONObject(target.toString()).put("view_id","other");check(!OverlayRules.matchesElement(target,changed),"different view framed");
  check(OverlayRules.coverageIncomplete(1200)&&!OverlayRules.coverageIncomplete(0),"coverage flag invalid");
  ConvergenceRules linked=new ConvergenceRules();JSONObject linkedClick=new JSONObject(click.toString()).put("details",frontend);linked.accept(linkedClick);check(linked.interactionFor(event(60,"trafic",1400))!=null,"legacy live finding did not receive click");check(linked.interactionFor(event(61,"trafic",6000))==null&&linked.interactionFor(event(62,"trafic",1400).put("clock_scope_id","other"))==null,"old or foreign clock click attached");
  check(OverlayRules.healthy(true,true,true,true,true,true),"all operational not green");check(!OverlayRules.healthy(true,true,true,false,true,true),"green without AppOps");check(OverlayRules.healthy(true,true,true,true,false,false),"optional VPN incorrectly made runtime unhealthy");check(!OverlayRules.coverageComplete(true,false,false),"missing visual evidence should keep coverage partial");check(!OverlayRules.coverageComplete(true,true,true),"known coverage gap should keep coverage partial");JSONArray alerts=new JSONArray().put(EventStore.object("id",184)).put(EventStore.object("id",185)).put(EventStore.object("id",186));JSONArray shown=OverlayRules.visible(alerts);check(shown.length()==2&&shown.getJSONObject(0).getLong("id")==184&&OverlayRules.remaining(5,shown)==3,"alert IDs/overflow wrong");
  check(!VisualEvidencePolicy.retain(0,true,true)&&!VisualEvidencePolicy.retain(1,false,true)&&!VisualEvidencePolicy.retain(1,true,false)&&VisualEvidencePolicy.retain(1,true,true),"crop without committed matching finding");check(VisualEvidencePolicy.failure(6).equals("SECURE_WINDOW")&&VisualEvidencePolicy.failure(3).equals("ANDROID_RATE_LIMIT"),"coverage refusal misclassified");
  AnomalyRules ar=new AnomalyRules();AnomalyRules.Settings settings=new AnomalyRules.Settings();settings.failureCount=8;List<AnomalyRules.Finding> observed=new ArrayList<>();
  AnomalyRules.Event success=new AnomalyRules.Event();success.id=1;success.elapsed=1000;success.wall=1000;success.category="trafic";success.uid=10371;success.packages=new String[]{"example.chat"};success.flow="success";success.destination="192.0.2.10:443";success.port=443;success.tx=80;success.rx=60;success.error=0;success.result="connecté";ar.accept(success,settings,observed::add);
  for(int i=0;i<8;i++){AnomalyRules.Event fail=new AnomalyRules.Event();fail.id=2+i;fail.elapsed=1100+i;fail.wall=1100+i;fail.category="trafic";fail.uid=10371;fail.packages=success.packages;fail.flow="failure-"+i;fail.port=443;fail.tx=80;fail.rx=60;fail.closed=true;fail.error=101;fail.result="injoignable";fail.destination="[2001:db8::2]:443";ar.accept(fail,settings,observed::add);}check(observed.isEmpty(),"successful alternate path still produced user anomaly");
  ar=new AnomalyRules();observed.clear();
  for(int i=0;i<8;i++){AnomalyRules.Event fail=new AnomalyRules.Event();fail.id=20+i;fail.elapsed=2000+i;fail.wall=2000+i;fail.category="trafic";fail.uid=10371;fail.packages=success.packages;fail.flow="isolated-failure-"+i;fail.port=443;fail.tx=80;fail.rx=60;fail.closed=true;fail.error=101;fail.result="injoignable";fail.destination="[2001:db8::3]:443";ar.accept(fail,settings,observed::add);}check(observed.size()==1&&"PATH_FAILURE".equals(observed.get(0).facts.get("connectivity_status"))&&"false".equals(observed.get(0).facts.get("other_substantial_flow_observed")),"isolated repeated path failure disappeared");
  AnomalyRules.Event health=new AnomalyRules.Event();health.id=20;health.elapsed=2000;health.category="sensor-health";health.problem="SECURE_WINDOW";health.action="VISUAL_COVERAGE_UNAVAILABLE";ar.accept(health,settings,observed::add);check(observed.get(observed.size()-1).type.equals("coverage"),"secure capture labelled app anomaly");
 }
 public static void main(String[] args)throws Exception{
  baseRules();Context context=new Context(new File(args[0]));monitor=AnomalyMonitor.get(context);SQLiteDatabase db=monitor.getWritableDatabase();
  JSONObject network=event(1,"trafic",1000);ConvergenceRules.details(network).put("tx_bytes",100).put("rx_bytes",200);monitor.pedigree(network,true);ConvergenceRules.details(network).put("tx_bytes",80);monitor.pedigree(network,true);JSONObject later=event(2,"trafic",2000);ConvergenceRules.details(later).put("flow_correlation_id","flow-1");JSONObject p=monitor.pedigree(later,false);check(p.getString("status").equals("KNOWN_FOR_APP")&&p.getLong("sessions")==1&&p.getLong("tx_bytes")==100,"cumulative snapshots summed or known endpoint lost");
  monitor.pedigree(later,true);p=monitor.pedigree(event(3,"trafic",3000),true);p=monitor.pedigree(event(4,"trafic",4000),false);check(p.getLong("sessions")==2&&p.getLong("tx_bytes")==100,"unknown volume fabricated or session dedup wrong");
  JSONObject different=event(5,"trafic",5000);ConvergenceRules.details(different).getJSONObject("app_identity").put("version_code",219);check(monitor.pedigree(different,false).getString("history_status").equals("NEW_FOR_APP"),"version pedigree leaked");
  JSONObject f=EventStore.object("group_key","live:test","rule","test","kind","anomaly","title","Synthetic","severity","attention","first_ms",1000,"last_ms",1200,"last_event_id",3,"evidence_ids",new JSONArray());Method save=AnomalyMonitor.class.getDeclaredMethod("saveLive",JSONObject.class);save.setAccessible(true);save.invoke(monitor,f);check(ScreenIntegrityService.committed==1,"persist/notify missing");long id=monitor.alerts().getJSONObject(0).getLong("id");
  JSONObject summary=monitor.summary();check(summary.getLong("unread")==1,"unread count wrong");JSONObject page=monitor.page("anomaly",true,0,100,"");check(page.getJSONArray("rows").length()==1&&page.getLong("total")==1,"recalculation hides persisted finding");check(monitor.finding(id).getLong("id")==id,"deep link wrong finding");int notifications=ScreenIntegrityService.notifications;monitor.change("review",String.valueOf(id));check(monitor.summary().getLong("unread")==0&&monitor.alerts().length()==0&&ScreenIntegrityService.notifications>notifications,"review did not update overlay count");save.invoke(monitor,f);check(monitor.summary().getLong("anomalies")==1,"duplicate finding persisted");
  JSONObject coverage=new JSONObject(f.toString()).put("group_key","live:coverage").put("kind","coverage");int beforeCoverage=ScreenIntegrityService.committed;save.invoke(monitor,coverage);check(ScreenIntegrityService.committed==beforeCoverage&&!monitor.finding(coverage.getLong("id")).getBoolean("overlay_eligible"),"health emitted an application highlight");check(monitor.summary().getLong("unread")==0&&monitor.page("coverage",false,0,100,"").getLong("total")==1,"sensor health mixed with app count");
  JSONObject old=EventStore.object("rule","failures","kind","anomaly","title","Historical","severity","attention","evidence_ids",new JSONArray());
  android.content.ContentValues oldValues=new android.content.ContentValues();oldValues.put("group_key",monitor.summary().optLong("revision")+":historical");oldValues.put("kind","anomaly");oldValues.put("rule","failures");oldValues.put("last_event_id",1);oldValues.put("first_ms",1);oldValues.put("last_ms",1);oldValues.put("occurrences",1);oldValues.put("payload",old.toString());db.insertOrThrow("findings",null,oldValues);
  check(monitor.summary().getLong("unread")==0&&monitor.summary().getLong("historical_unread")==1&&monitor.alerts().length()==0,"history flooded real-time counter");
  check(monitor.page("anomaly",true,0,100,"").getLong("total")==0&&monitor.page("anomaly",false,0,100,"").getLong("total")==2,"history hidden or unread list mismatched");
  JSONObject a=new JSONObject(f.toString()).put("group_key","live:reset-a"),b=new JSONObject(f.toString()).put("group_key","live:reset-b");save.invoke(monitor,a);save.invoke(monitor,b);long ceiling=monitor.summary().getLong("alert_ceiling_id");JSONObject laterAlert=new JSONObject(f.toString()).put("group_key","live:after-reset");save.invoke(monitor,laterAlert);
  monitor.change("review-all",String.valueOf(ceiling));check(monitor.summary().getLong("unread")==1&&monitor.alerts().length()==1&&monitor.alerts().getJSONObject(0).getLong("id")==laterAlert.getLong("id"),"reset erased a later alert or failed");
  check(monitor.finding(a.getLong("id")).getBoolean("reviewed")&&monitor.finding(b.getLong("id")).getBoolean("reviewed")&&monitor.page("anomaly",false,0,100,"").getLong("total")==5,"reset deleted proof dossiers");
  monitor.change("review-all",String.valueOf(monitor.summary().getLong("alert_ceiling_id")));check(monitor.summary().getLong("unread")==0&&monitor.alerts().length()==0,"bulk reset not zero");
  monitor.change("review-all","0");check(monitor.summary().getLong("unread")==0,"empty reset failed");
  java.lang.reflect.Field convField=AnomalyMonitor.class.getDeclaredField("convergence");convField.setAccessible(true);ConvergenceRules activeRules=(ConvergenceRules)convField.get(monitor);JSONObject liveClick=event(200,"frontend",1000);ConvergenceRules.details(liveClick).put("event_kind","CLICK").put("element_source","EVENT_NODE").put("window_id",7).put("package_name","example.chat").put("captured_elapsed_ms",1000).put("element",EventStore.object("text","Partager","class","Button","content_description","","view_id","share","visible",true,"bounds",new JSONArray(Arrays.asList(1,2,30,40))));activeRules.accept(liveClick);
  AnomalyRules.Finding lf=new AnomalyRules.Finding();lf.key="live:rules:linked";lf.type="anomaly";lf.rule="failures";lf.wall=101400;lf.eventId=201;lf.explanation="PATH_FAILURE";lf.evidence.add(201L);Method saveRule=AnomalyMonitor.class.getDeclaredMethod("saveFinding",SQLiteDatabase.class,AnomalyRules.Finding.class,JSONObject.class);saveRule.setAccessible(true);int committed=ScreenIntegrityService.committed;saveRule.invoke(monitor,db,lf,event(201,"trafic",1400));long linkedId=monitor.alerts().getJSONObject(0).getLong("id");check(ScreenIntegrityService.committed==committed+1&&monitor.finding(linkedId).getJSONObject("frontend").getString("clock_scope_id").equals("fixture"),"legacy finding bounds not persisted before highlight");
  monitor.change("review",String.valueOf(linkedId));saveRule.invoke(monitor,db,lf,event(202,"trafic",1500));check(ScreenIntegrityService.committed==committed+1&&monitor.summary().getLong("unread")==0,"reviewed finding flashed again");
  android.content.ContentValues obsolete=new android.content.ContentValues();obsolete.put("group_key","999:obsolete");obsolete.put("kind","anomaly");obsolete.put("rule","failures");obsolete.put("last_event_id",1);obsolete.put("first_ms",1);obsolete.put("last_ms",1);obsolete.put("occurrences",1);obsolete.put("payload",old.toString());long obsoleteId=db.insertOrThrow("findings",null,obsolete);
  StringWriter exported=new StringWriter();monitor.export(exported);JSONObject exportedReport=new JSONObject(exported.toString());JSONArray exportRows=exportedReport.getJSONArray("findings");boolean oldRetained=false,obsoleteExported=false,liveRetained=false,healthRetained=false;
  for(int i=0;i<exportRows.length();i++){JSONObject item=exportRows.getJSONObject(i);if(item.getLong("id")==obsoleteId)obsoleteExported=true;if("Historical".equals(item.optString("title")))oldRetained="HISTORICAL_REPLAY".equals(item.optString("origin"))&&!item.optBoolean("overlay_eligible");if(item.getLong("id")==linkedId)liveRetained="LIVE_OBSERVATION".equals(item.optString("origin"));if("coverage".equals(item.optString("kind")))healthRetained=!item.optBoolean("overlay_eligible");}
  check(oldRetained&&liveRetained&&healthRetained&&!obsoleteExported,"export origin/history/health scope wrong");check(monitor.finding(obsoleteId).getLong("id")==obsoleteId,"superseded proof deleted");
  AnomalyMonitor.liveError="live-failure";check(monitor.summary().getString("error").equals("live-failure"),"history success hid live sensor failure");AnomalyMonitor.liveError="";
  File dir=new File(args[0],"visual");dir.mkdirs();File expired=new File(dir,"expired.png"),newest=new File(dir,"new.png"),extra=new File(dir,"extra.png");for(File file:new File[]{expired,newest,extra})try(FileOutputStream out=new FileOutputStream(file)){out.write(new byte[10]);}long now=System.currentTimeMillis();expired.setLastModified(now-VisualEvidencePolicy.RETENTION_MS-1);extra.setLastModified(now-10);newest.setLastModified(now);VisualEvidencePolicy.prune(dir,now,VisualEvidencePolicy.RETENTION_MS,20,1);check(newest.exists()&&!expired.exists()&&!extra.exists(),"retention unbounded");
  System.out.println("Convergence production rules/SQLite/evidence policies: "+checks+" checks passed");
 }
}'''
with tempfile.TemporaryDirectory() as folder:
 root=Path(folder);src=root/'src';classes=root/'classes';classes.mkdir()
 for name,body in stubs.items():
  p=src/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(body)
 (src/'fr/erick/journallocal/ConvergenceProbe.java').write_text(probe)
 files=list(src.rglob('*.java'))+[JAVA/(n+'.java') for n in ('AivConfig','TrackerMatcher','AnomalyRules','ConvergenceRules','AnomalyMonitor','EndpointContextRules','OverlayRules','VisualEvidencePolicy')]
 subprocess.run(['javac','-encoding','UTF-8','-cp',cp,'-d',str(classes),*map(str,files)],check=True,timeout=40)
 subprocess.run(['java','-cp',str(classes)+os.pathsep+cp,'fr.erick.journallocal.ConvergenceProbe',str(root/'data')],check=True,timeout=40)
