package fr.erick.journallocal;

import android.content.Context;
import android.content.pm.*;
import org.json.*;
import java.io.*;
import java.nio.file.Files;

/** Real controller and durable files; only Android/Shizuku observations are simulated. */
public final class PermissionMaintenanceTest {
    static final String BACK="android.permission.ACCESS_BACKGROUND_LOCATION",CAMERA="android.permission.CAMERA",OVERLAY="android.permission.SYSTEM_ALERT_WINDOW",NET="android.permission.INTERNET";
    static int checks;
    static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    static void await()throws Exception{long end=System.currentTimeMillis()+30000;while(PermissionMaintenance.busy()&&System.currentTimeMillis()<end)Thread.sleep(5);check(!PermissionMaintenance.busy(),"bounded completion");}
    static void tick(Context c)throws Exception{PermissionMaintenance.request(c);await();}
    // These regressions exercise unsolicited returns, without an Android user-choice marker.
    static void app(Context c,String pkg,int uid,String... names){PermissionControlIntegrationTest.app(c,pkg,uid,names);for(String name:names)c.pm.flags.put(pkg+"|"+name,"");}
    static boolean granted(Context c,String pkg,String name){return c.pm.checkPermission(name,pkg)==PackageManager.PERMISSION_GRANTED;}
    static JSONObject state(Context c)throws Exception{return PermissionMaintenance.state(c);}
    static JSONObject policy(Context c)throws Exception{return PermissionMaintenance.exportState(c).getJSONObject("policy");}
    public static void main(String[] args)throws Exception{
        Context c=new Context(new File(args[0]),new File(args[1]));ControlShell.context=c;PermissionControl.setReviewGroup(c,"capture",true);
        check(PermissionMaintenance.displayStatus(c).contains("enregistrer les refus actuels"),"initial state describes activation instead of ambiguous waiting");
        app(c,"com.example.cleaned",11111,BACK,CAMERA);c.pm.grants.put("com.example.cleaned|"+BACK,false);c.pm.grants.put("com.example.cleaned|"+CAMERA,false);
        app(c,"com.example.overlay",11112,OVERLAY);c.pm.ops.put("com.example.overlay","ignore");
        app(c,"com.example.locked",11113,BACK);c.pm.grants.put("com.example.locked|"+BACK,false);c.pm.flags.put("com.example.locked|"+BACK,"POLICY_FIXED");
        app(c,"com.example.protected",11114,BACK);c.pm.grants.put("com.example.protected|"+BACK,false);c.pm.guards.put("com.example.protected","Protection AIV : rôle essentiel");
        app(c,"com.example.normal",11115,NET);c.pm.grants.put("com.example.normal|"+NET,false);c.pm.protection.put(NET,0);
        app(c,"com.example.unknown",11116,BACK);c.pm.grants.put("com.example.unknown|"+BACK,false);
        app(c,"com.example.shared1",11117,BACK);app(c,"com.example.shared2",11117,BACK);for(String pkg:new String[]{"com.example.shared1","com.example.shared2"}){c.pm.guards.put(pkg,"Portée UID partagé");c.pm.grants.put(pkg+"|"+BACK,false);}
        app(c,"com.example.allowed",11118,CAMERA);
        PermissionMaintenance.prepare(c);await();
        check(state(c).getBoolean("enabled")&&state(c).getInt("rights")==3,"verified manual runtime denials and special access form baseline");
        java.lang.reflect.Field statusField=PermissionMaintenance.class.getDeclaredField("status");statusField.setAccessible(true);statusField.set(null,"Maintien non activé");
        check(state(c).getString("status").startsWith("Maintien activé"),"persisted activation survives a process status reset");
        check(state(c).getInt("known")==9&&state(c).getJSONArray("baseline_errors").length()==1,"unknown Shell state reported; current visible apps recorded");
        check(ControlShell.mutations==0,"activation never removes a newly granted right or creates grants");
        check(!policy(c).getJSONObject("targets").has("com.example.normal|"+NET),"normal INTERNET permission cannot become a runtime policy");
        c.pm.grants.put("com.example.cleaned|"+BACK,true);c.pm.grants.put("com.example.cleaned|"+CAMERA,true);c.pm.ops.put("com.example.overlay","allow");tick(c);
        check(ControlShell.mutations==3&&!granted(c,"com.example.cleaned",BACK)&&!granted(c,"com.example.cleaned",CAMERA)&&"ignore".equals(c.pm.ops.get("com.example.overlay")),"regranted runtime and AppOp states corrected and verified");
        check(state(c).getLong("corrections")==3,"confirmed correction count");int before=ControlShell.mutations;tick(c);check(ControlShell.mutations==before,"unchanged refused states are idempotent");
        check(granted(c,"com.example.allowed",CAMERA),"an initially allowed right is never inferred to be denied");
        check(EventStore.receipts.stream().filter(r->"pending".equals(r.optString("phase"))).count()==3&&EventStore.receipts.stream().filter(r->"confirmed".equals(r.optString("phase"))).count()==3,"journal correlates durable before and verified after receipts");
        c.pm.grants.put("com.example.cleaned|"+CAMERA,true);PermissionMaintenance.pause(c);tick(c);check(granted(c,"com.example.cleaned",CAMERA),"pause forbids subsequent commands");check(state(c).getString("status").equals("Maintien en pause"),"paused reference is distinguished from initial activation");PermissionMaintenance.resume(c);await();check(!granted(c,"com.example.cleaned",CAMERA),"resume uses existing baseline without absorbing the regrant");
        c.pm.grants.put("com.example.cleaned|"+BACK,true);rikka.shizuku.Shizuku.available=false;tick(c);check(granted(c,"com.example.cleaned",BACK)&&state(c).getBoolean("enabled"),"Shizuku loss preserves intent without executing commands");check(state(c).getString("status").startsWith("En attente de Shizuku"),"missing Shizuku has an actionable waiting reason");rikka.shizuku.Shizuku.available=true;tick(c);check(!granted(c,"com.example.cleaned",BACK),"Shizuku return resumes correction");
        c.pm.grants.put("com.example.cleaned|"+BACK,true);EventStore.pendingHook=()->rikka.shizuku.Shizuku.available=false;before=ControlShell.mutations;tick(c);check(ControlShell.mutations==before&&granted(c,"com.example.cleaned",BACK)&&state(c).getBoolean("enabled")&&policy(c).getJSONObject("targets").getJSONObject("com.example.cleaned|"+BACK).getInt("failures")==0,"Shizuku loss during receipt write forbids command without exhausting target retries");rikka.shizuku.Shizuku.available=true;tick(c);check(!granted(c,"com.example.cleaned",BACK),"mid-command availability recovery retains the refusal policy");
        Continuous.active=false;c.pm.grants.put("com.example.cleaned|"+BACK,true);tick(c);check(granted(c,"com.example.cleaned",BACK),"collector stop also pauses scheduled maintenance");check(state(c).getString("status").startsWith("En attente de la collecte AIV"),"collector stop is not reported as active");Continuous.active=true;tick(c);
        c.pm.apps.get("com.example.cleaned").versionCode++;c.pm.apps.get("com.example.cleaned").lastUpdateTime++;c.pm.grants.put("com.example.cleaned|"+CAMERA,true);tick(c);check(!granted(c,"com.example.cleaned",CAMERA)&&state(c).getInt("pending_count")==0,"same-signer update retains previously chosen denials");
        c.pm.grants.put("com.example.cleaned|"+BACK,true);EventStore.pendingHook=()->c.pm.guards.put("com.example.cleaned","Protection AIV : nouveau rôle");before=ControlShell.mutations;tick(c);check(ControlShell.mutations==before&&granted(c,"com.example.cleaned",BACK),"role changed during receipt persistence prevents Shell mutation");c.pm.guards.remove("com.example.cleaned");tick(c);
        app(c,"com.example.newapp",12000,CAMERA);tick(c);check(state(c).getInt("pending_count")==1&&c.pm.getApplicationEnabledSetting("com.example.newapp")==0,"new app detected with blocking opt-in off");
        PermissionMaintenance.setBlocksNew(c,true);await();check(c.pm.getApplicationEnabledSetting("com.example.newapp")==3&&(c.pm.apps.get("com.example.newapp").applicationInfo.flags&ApplicationInfo.FLAG_STOPPED)!=0,"new app disabled and stopped after detection");
        JSONObject pending=state(c).getJSONObject("pending").getJSONObject("com.example.newapp");String stamp=pending.getJSONObject("owner").getString("stamp");PermissionMaintenance.approve(c,"com.example.newapp",stamp);check(c.pm.getApplicationEnabledSetting("com.example.newapp")==0&&state(c).getInt("pending_count")==0,"explicit approval restores original enabled state and records owner");tick(c);check(c.pm.getApplicationEnabledSetting("com.example.newapp")==0,"approved app is not disabled again");
        app(c,"com.example.unverified",12010,CAMERA);c.pm.apps.get("com.example.unverified").signer="";tick(c);
        check("identity_unverified".equals(state(c).getJSONObject("pending").getJSONObject("com.example.unverified").getString("phase"))&&c.pm.getApplicationEnabledSetting("com.example.unverified")==0,"unverifiable new app is visible for review without fabricated owner or mutation");c.pm.apps.remove("com.example.unverified");
        app(c,"com.example.approvaldisk",12011,CAMERA);tick(c);stamp=state(c).getJSONObject("pending").getJSONObject("com.example.approvaldisk").getJSONObject("owner").getString("stamp");before=ControlShell.mutations;android.util.AtomicFile.failPolicy=true;boolean diskFailure=false;try{PermissionMaintenance.approve(c,"com.example.approvaldisk",stamp);}catch(IOException e){diskFailure=true;}android.util.AtomicFile.failPolicy=false;
        check(diskFailure&&ControlShell.mutations==before&&c.pm.getApplicationEnabledSetting("com.example.approvaldisk")==3,"approval disk failure leaves app disabled and issues no enable");PermissionMaintenance.approve(c,"com.example.approvaldisk",stamp);
        app(c,"com.example.approvalrace",12012,CAMERA);tick(c);stamp=state(c).getJSONObject("pending").getJSONObject("com.example.approvalrace").getJSONObject("owner").getString("stamp");EventStore.pendingHook=()->c.pm.guards.put("com.example.approvalrace","Protection AIV : rôle changé");before=ControlShell.mutations;boolean roleFailure=false;try{PermissionMaintenance.approve(c,"com.example.approvalrace",stamp);}catch(IOException e){roleFailure=true;}
        check(roleFailure&&ControlShell.mutations==before&&c.pm.getApplicationEnabledSetting("com.example.approvalrace")==3&&!state(c).getJSONObject("pending").has("com.example.approvalrace"),"approval persists but a role change during receipt write prevents enabling");
        app(c,"com.example.newsystem",12001,CAMERA);c.pm.apps.get("com.example.newsystem").applicationInfo.flags|=ApplicationInfo.FLAG_SYSTEM;app(c,"com.example.newshared1",12002,CAMERA);app(c,"com.example.newshared2",12002,CAMERA);app(c,"com.example.workprofile",112003,CAMERA);tick(c);
        check(c.pm.getApplicationEnabledSetting("com.example.newsystem")==0&&c.pm.getApplicationEnabledSetting("com.example.newshared1")==0&&state(c).getInt("pending_count")==4,"system components and shared UIDs require review; another profile is excluded");
        app(c,"com.example.updatedsystem",12013,CAMERA);c.pm.apps.get("com.example.updatedsystem").applicationInfo.flags|=ApplicationInfo.FLAG_UPDATED_SYSTEM_APP;tick(c);check(c.pm.getApplicationEnabledSetting("com.example.updatedsystem")==0&&"protected_review".equals(state(c).getJSONObject("pending").getJSONObject("com.example.updatedsystem").getString("phase")),"updated system component is also exempt from automatic disable");
        c.pm.apps.get("com.example.newapp").signer="replacement-signer";c.pm.apps.get("com.example.newapp").lastUpdateTime++;tick(c);check(state(c).getJSONObject("pending").has("com.example.newapp")&&c.pm.getApplicationEnabledSetting("com.example.newapp")==3,"different signer is not accepted as a normal update");
        app(c,"com.example.refused",12004,CAMERA);ControlShell.refuse="com.example.refused";for(int i=0;i<4;i++)tick(c);check(state(c).getJSONObject("pending").getJSONObject("com.example.refused").getInt("failures")==3&&c.pm.getApplicationEnabledSetting("com.example.refused")==0,"rejected disable is reported and retries stop at three");ControlShell.refuse="";
        c.pm.flags.put("com.example.cleaned|"+BACK,"SYSTEM_FIXED");c.pm.grants.put("com.example.cleaned|"+BACK,true);before=ControlShell.mutations;for(int i=0;i<4;i++)tick(c);check(granted(c,"com.example.cleaned",BACK)&&ControlShell.mutations==before&&state(c).getInt("suspended_rights")==1,"new Android lock suspends that right without repeated Shell attempts");c.pm.flags.put("com.example.cleaned|"+BACK,"USER_SET");c.pm.grants.put("com.example.cleaned|"+BACK,false);PermissionMaintenance.prepare(c);await();check(state(c).getInt("suspended_rights")==0,"explicit addition of freshly verified denials can clear a suspension");
        app(c,"com.example.manualmore",12005,CAMERA);c.pm.grants.put("com.example.manualmore|"+CAMERA,false);PermissionMaintenance.prepare(c);await();check(!policy(c).getJSONObject("known").has("com.example.manualmore"),"adding denied states does not silently approve an unknown installed app");
        c.pm.grants.put("com.example.cleaned|"+CAMERA,true);before=ControlShell.mutations;check(ControlCoordinator.acquire(),"exclusive lease available");PermissionMaintenance.request(c);check(!PermissionMaintenance.busy()&&ControlShell.mutations==before,"maintenance never overlaps another controller");ControlCoordinator.release();
        EventStore.writable=false;tick(c);check(!state(c).getBoolean("enabled")&&granted(c,"com.example.cleaned",CAMERA)&&ControlShell.mutations==before,"unwritable audit prevents commands and suspends maintenance");EventStore.writable=true;PermissionMaintenance.resume(c);await();
        c.pm.grants.put("com.example.cleaned|"+CAMERA,true);ControlShell.failResultLog=true;tick(c);check(!state(c).getBoolean("enabled")&&!granted(c,"com.example.cleaned",CAMERA)&&PermissionMaintenance.exportState(c).getJSONObject("last_action").getString("phase").equals("confirmed"),"post-command journal failure preserves file receipt and suspends follow-up");ControlShell.failResultLog=false;EventStore.writable=true;PermissionMaintenance.resume(c);await();
        JSONObject plan=PermissionControl.preview(c,new JSONArray().put(EventStore.object("package","com.example.allowed","permissions",new JSONArray().put(CAMERA))));PermissionControl.apply(c,plan.getString("stamp"));PermissionControlIntegrationTest.waitForJob();
        check(!granted(c,"com.example.allowed",CAMERA)&&policy(c).getJSONObject("targets").has("com.example.allowed|"+CAMERA),"actual manual apply records its confirmed denial in existing maintenance policy");PermissionControl.restore(c);PermissionControlIntegrationTest.waitForJob();tick(c);
        check(granted(c,"com.example.allowed",CAMERA)&&!policy(c).getJSONObject("targets").has("com.example.allowed|"+CAMERA),"actual restoration durably excludes denial before granting and is not undone");
        plan=PermissionControl.preview(c,new JSONArray().put(EventStore.object("package","com.example.allowed","permissions",new JSONArray().put(CAMERA))));PermissionControl.apply(c,plan.getString("stamp"));PermissionControlIntegrationTest.waitForJob();c.pm.grants.put("com.example.allowed|"+CAMERA,true);PermissionControl.restore(c);PermissionControlIntegrationTest.waitForJob();tick(c);
        check(granted(c,"com.example.allowed",CAMERA)&&!policy(c).getJSONObject("targets").has("com.example.allowed|"+CAMERA),"explicit restore also excludes an already manually restored right");
        c.pm.grants.put("com.example.cleaned|"+CAMERA,true);ControlShell.noEffect="com.example.cleaned";tick(c);check(granted(c,"com.example.cleaned",CAMERA)&&"unverified".equals(PermissionMaintenance.exportState(c).getJSONObject("last_action").getString("phase")),"exit zero without observed state change never confirms a correction");ControlShell.noEffect="";tick(c);
        c.pm.apps.get("com.example.cleaned").firstInstallTime++;c.pm.grants.put("com.example.cleaned|"+CAMERA,true);tick(c);check(granted(c,"com.example.cleaned",CAMERA)&&state(c).getJSONObject("pending").has("com.example.cleaned"),"same signer and UID reused by a reinstall do not inherit old denials");
        JSONObject exported=PermissionMaintenance.exportState(c);check(exported.has("policy")&&exported.has("last_action")&&Files.size(new File(c.getFilesDir(),"permission-maintenance/policy.json").toPath())>0,"state and last receipt recoverable from durable files");
        Context bounded=new Context(new File(c.getFilesDir(),"bounded"),new File(args[1]));bounded.getFilesDir().mkdirs();ControlShell.context=bounded;for(int i=0;i<25;i++){String pkg="com.example.bound"+String.format("%02d",i);app(bounded,pkg,13000+i,BACK);bounded.pm.grants.put(pkg+"|"+BACK,false);}PermissionMaintenance.prepare(bounded);await();
        bounded.pm.grants.replaceAll((k,v)->true);before=ControlShell.mutations;ControlShell.cancelAfter=before+1;tick(bounded);check(ControlShell.mutations-before==1,"stop finishes the current correction without starting another");ControlShell.cancelAfter=0;before=ControlShell.mutations;tick(bounded);check(ControlShell.mutations-before==12,"one maintenance pass issues at most twelve mutations");tick(bounded);check(bounded.pm.grants.values().stream().noneMatch(Boolean::booleanValue),"cursor rotation eventually covers every recorded runtime refusal");
        Context special=new Context(new File(c.getFilesDir(),"special"),new File(args[1]));special.getFilesDir().mkdirs();ControlShell.context=special;for(int i=0;i<25;i++){String pkg="com.example.op"+String.format("%02d",i);app(special,pkg,14000+i,OVERLAY);special.pm.ops.put(pkg,"ignore");}PermissionMaintenance.prepare(special);await();ControlShell.opQueries=0;tick(special);check(ControlShell.opQueries==20,"unchanged special accesses are checked in bounded pages of twenty");special.pm.ops.put("com.example.op24","allow");tick(special);check("ignore".equals(special.pm.ops.get("com.example.op24")),"special-access cursor reaches targets beyond the first page");
        System.out.println("PermissionMaintenance integration: "+checks+" checks passed");
    }
}
