#!/usr/bin/env python3
from pathlib import Path
import os,tempfile,subprocess
root=Path(__file__).parents[1]
for edition in ('FREE','FOUNDER_FULL','OWNER_INTERNAL'):
 for preview in (False,True):
  with tempfile.TemporaryDirectory() as tmp:
   out=Path(tmp);pkg=out/'fr/erick/journallocal';pkg.mkdir(parents=True)
   ctx=out/'android/content/Context.java';ctx.parent.mkdir(parents=True);ctx.write_text('package android.content;public class Context{public Context getApplicationContext(){return this;}}')
   (pkg/'Fixtures.java').write_text('''package fr.erick.journallocal;import org.json.*;class LicenseClient{static boolean valid;static boolean active(Object c){return valid;}}class EventStore{static JSONObject object(Object...v){JSONObject o=new JSONObject();for(int i=0;i<v.length;i+=2)o.put((String)v[i],v[i+1]);return o;}}''')
   (pkg/'EditionConfig.java').write_text('package fr.erick.journallocal;class EditionConfig{static final boolean TEST_PREVIEW='+str(preview).lower()+';static final String EDITION="'+edition+'";}')
   (pkg/'ProductAccessTest.java').write_text('''package fr.erick.journallocal;import android.content.Context;public class ProductAccessTest{public static void main(String[]args){Context c=new Context();ProductAccess.initialize(c);LicenseClient.valid=false;if("OWNER_INTERNAL".equals(EditionConfig.EDITION)&&!EditionConfig.TEST_PREVIEW){if(!ProductAccess.ownerBuild()||ProductAccess.verifiedTier()!=3)throw new AssertionError("Owner functionality lost");System.out.println("PASS explicit internal owner control; separate from public editions");return;}ProductAccess.setDemoTier(c,3);if(ProductAccess.verifiedTier()!=1||ProductAccess.ownerBuild())throw new AssertionError("Owner/demo override remains");LicenseClient.valid=true;boolean founder="FOUNDER_FULL".equals(EditionConfig.EDITION);if(ProductAccess.paidEnabled(c)!=founder)throw new AssertionError("APK grants payment or FREE allows Shizuku");LicenseClient.valid=false;if(ProductAccess.fullUi(c)!=(EditionConfig.TEST_PREVIEW&&founder))throw new AssertionError("Preview routing invalid");try{ProductAccess.requireFounder();throw new AssertionError("Invalid proof unlocks");}catch(SecurityException expected){}System.out.println("PASS production ProductAccess "+EditionConfig.EDITION+": owner/demo cannot unlock; edition AND proof required");}}''')
   cp=os.environ['AIV_JSON_JAR'];files=list(out.rglob('*.java'))+[root/'app/src/main/java/fr/erick/journallocal/ProductAccess.java'];subprocess.run(['javac','-cp',cp,'-d',tmp,*map(str,files)],check=True);subprocess.run(['java','-cp',tmp+os.pathsep+cp,'fr.erick.journallocal.ProductAccessTest'],check=True)
