apiVersion: v1
kind: Namespace
metadata:
  name: aiv-prototype
  labels:
    app.kubernetes.io/part-of: all-in-visible
    app.kubernetes.io/managed-by: github-actions
    aiv.example/environment: prototype
