#!/usr/bin/env python3
"""Generate public Android constants. Never read credentials or environment secrets."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = {
    'work': {'events': (1, 1024), 'verify_rows': (1, 4096), 'stats_rows': (1, 4096), 'slice_ms': (1, 1000), 'min_pause_ms': (100, 60000)},
    'anomaly': {'window_ms': (1000, 86400000), 'group_ms': (1000, 86400000), 'failure_count_default': (2, 100), 'upload_mib_default': (1, 1024)},
    'collection': {'gap_ms': (1000, 86400000), 'clock_drift_ms': (1, 60000), 'inventory_interval_ms': (60000, 86400000), 'heartbeat_ms': (1000, 3600000)},
    'main': {'inventory_max_age_ms': (1000, 604800000), 'threshold_bytes_default': (0, 2147483647), 'config_max_chars': (1024, 1048576), 'list_max_items': (1, 1000)},
    'reference': {'import_max_bytes': (1024, 67108864), 'max_apps': (1, 100000), 'app_max_chars': (1024, 1048576), 'max_expected_ips': (1, 1000)},
}

def validate(data):
    if set(data) != {'schema', 'paths', *SPEC} or data['schema'] != 'aiv-config/1':
        raise ValueError('Invalid config schema or unknown sections')
    paths=data['paths']
    if not isinstance(paths, dict) or set(paths) != {'exports_cache', 'cleanup_snapshot'}:
        raise ValueError('Invalid paths')
    for value in paths.values():
        if not isinstance(value, str) or not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_.-]{0,63}', value):
            raise ValueError('Paths must be single local names, never absolute paths')
    for section, fields in SPEC.items():
        if not isinstance(data[section], dict) or set(data[section]) != set(fields):
            raise ValueError('Missing/unknown fields: ' + section)
        for name, (low, high) in fields.items():
            value = data[section][name]
            if type(value) is not int or not low <= value <= high:
                raise ValueError(f'Invalid {section}.{name}: expected integer {low}..{high}')
    if data['collection']['gap_ms'] <= data['collection']['heartbeat_ms']:
        raise ValueError('Collection gap must exceed heartbeat interval')
    if data['anomaly']['group_ms'] < data['anomaly']['window_ms']:
        raise ValueError('Anomaly group must cover the window')
    if data['reference']['app_max_chars'] > data['reference']['import_max_bytes']:
        raise ValueError('Reference record exceeds import limit')
    return data

def render(data):
    validate(data)
    digest = hashlib.sha256(json.dumps(data, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    lines = ['package fr.erick.journallocal;', '', '/** Generated by tools/generate_config.py; edit config/defaults.json. Public values only. */', 'public final class AivConfig {', '    private AivConfig() {}', f'    public static final String SHA256="{digest}";']
    for section, fields in SPEC.items():
        for name in fields:
            lines.append(f'    public static final int {section.upper()}_{name.upper()}={data[section][name]};')
    for name, value in data['paths'].items():
        lines.append(f'    public static final String PATHS_{name.upper()}={json.dumps(value)};')
    return '\n'.join([*lines, '}', ''])

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render(json.loads((ROOT/'config/defaults.json').read_text()))
    target = ROOT/'app/src/main/java/fr/erick/journallocal/AivConfig.java'
    if args.check:
        if not target.is_file() or target.read_text() != content:
            raise SystemExit('AivConfig.java is stale; run tools/generate_config.py')
    else:
        target.write_text(content)
