plugins { id 'com.android.application' }
android {
    namespace 'fr.erick.threeai'
    compileSdk { version = release(37) { minorApiLevel = 1 } }
    buildToolsVersion '36.0.0'
    defaultConfig {
        applicationId 'fr.erick.threeai'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '0.1.5'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildFeatures { aidl true; buildConfig true }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes {
        release { minifyEnabled false; ndk { abiFilters 'arm64-v8a' } }
        debug { ndk { abiFilters 'x86_64', 'arm64-v8a' } }
    }
}
dependencies {
    implementation 'org.mozilla.geckoview:geckoview:157.0.20261005135250'
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
